=== jumpinjackie/mapguide/MgDev/Common/Schema/ResourceDocumentHeader-1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:include schemaLocation="ResourceSecurity-1.0.0.xsd"/>
  <xs:element name="ResourceDocumentHeader" type="ResourceDocumentHeaderType">
    <xs:annotation>
      <xs:documentation>Resource Document Header</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="ResourceDocumentHeaderType">
    <xs:sequence>
      <xs:element name="General" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="IconName" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="Security" type="ResourceSecurityType"/>
      <xs:element name="Metadata" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Simple">
              <xs:complexType>
                <xs:sequence maxOccurs="unbounded">
                  <xs:element name="Property">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="Name" type="xs:string"/>
                        <xs:element name="Value" type="xs:string"/>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== jumpinjackie/mapguide/MgDev/UnitTest/TestData/Wfs/Sheboygan_CityLimits_Layer_Header.xml
<?xml version="1.0" encoding="UTF-8"?>
<ResourceDocumentHeader xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ResourceDocumentHeader-1.0.0.xsd">
  <General>
    <IconName>LayerDefinitionVector</IconName>
  </General>
  <Security xsi:noNamespaceSchemaLocation="ResourceSecurity-1.0.0.xsd">
    <Inherited>true</Inherited>
  </Security>
  <Metadata>
    <Simple>
      <Property xsi:noNamespaceSchemaLocation="Property-1.0.0.xsd">
        <Name>_Queryable</Name>
        <Value>1</Value>
      </Property>
      <Property xsi:noNamespaceSchemaLocation="Property-1.0.0.xsd">
        <Name>_Abstract</Name>
        <Value>City limits</Value>
      </Property>
      <Property xsi:noNamespaceSchemaLocation="Property-1.0.0.xsd">
        <Name>_Bounds</Name>
        <Value>&lt;Bounds SRS="EPSG:4326" west="-87.74" south="43.68" east="-87.69" north="43.815"/&gt;</Value>
      </Property>
      <Property xsi:noNamespaceSchemaLocation="Property-1.0.0.xsd">
        <Name>_Title</Name>
        <Value>CityLimits</Value>
      </Property>
      <Property xsi:noNamespaceSchemaLocation="Property-1.0.0.xsd">
        <Name>_Opaque</Name>
        <Value>0</Value>
      </Property>
      <Property xsi:noNamespaceSchemaLocation="Property-1.0.0.xsd">
        <Name>_IsPublished</Name>
        <Value>1</Value>
      </Property>
    </Simple>
  </Metadata>
</ResourceDocumentHeader>
