=== jumpinjackie/mapguide/Oem/dbxml-2.3.10/xerces-c-src/doc/style/dtd/book.dtd
<?xml encoding='ISO-8859-1'?>

<!-- STYLEBOOK BOOK DTD -->

<!-- import the external source-specific dtd -->
<!ENTITY % externalEntity SYSTEM "entities.ent">
%externalEntity;

<!ELEMENT book (resources?|document|hidden|faqs|changes|group|container|external|separator)+>
<!ATTLIST book title     CDATA #REQUIRED
               copyright CDATA #IMPLIED>

<!ELEMENT resources EMPTY>
<!ATTLIST resources source CDATA #REQUIRED>

<!ELEMENT document EMPTY>
<!ATTLIST document id     ID    #REQUIRED
                   source CDATA #REQUIRED
                   label  CDATA #REQUIRED>

<!ELEMENT hidden EMPTY>
<!ATTLIST hidden id     ID    #REQUIRED
                 source CDATA #REQUIRED>

<!ELEMENT faqs EMPTY>
<!ATTLIST faqs id     ID    #REQUIRED
               source CDATA #REQUIRED
               label  CDATA #REQUIRED>

<!ELEMENT changes EMPTY>
<!ATTLIST changes id     ID    #REQUIRED
                  source CDATA #REQUIRED
		  label  CDATA #REQUIRED>

<!ELEMENT group (entry)+>
<!ATTLIST group id    ID    #IMPLIED
                label CDATA #REQUIRED
		title CDATA #IMPLIED>

<!ELEMENT container (entry)+>
<!ATTLIST container id    ID    #IMPLIED
		source CDATA #REQUIRED
                label CDATA #REQUIRED>

<!ELEMENT entry EMPTY>
<!ATTLIST entry id     ID    #REQUIRED
                source CDATA #REQUIRED>

<!ELEMENT external EMPTY>
<!ATTLIST external label CDATA #REQUIRED
                   href  CDATA #REQUIRED>

<!ELEMENT separator EMPTY>

<!-- CVS $Revision: 173499 $ $Date: 2002-02-14 10:51:55 -0500 (Thu, 14 Feb 2002) $ -->

=== jumpinjackie/mapguide/MgDev/Oem/dbxml-2.3.10/xerces-c-src/doc/xerces-c_book.xml
<?xml version="1.0"?>
<!--
 * Copyright 1999-2005 The Apache Software Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
-->

<!DOCTYPE book SYSTEM "sbk:/style/dtd/book.dtd">

<book title="&XercesCName; Documentation" copyright="1999-2005 The Apache Software Foundation">

  &home;


  <separator/>

     <document id="index"       label="Readme"             source="readme.xml"/>
     <document id="charter"     label="Charter"             source="charter.xml"/>
     <document id="releases"    label="Release Info"     source="releases.xml"/>
     <hidden id="releases_archive"                   source="releases_archive.xml"/>
     &releases_plan;


  <separator/>

     <document id="install"     label="Installation"       source="install.xml"/>
     <external href="http://&XercesDistDir;"              label="Download"/>
     <document id="build"       label="Build Instructions" source="build.xml"/>
     <hidden   id="build-winunix" source="build-winunix.xml"/>
     <hidden   id="build-other" source="build-other.xml"/>
     <hidden   id="build-misc"  source="build-misc.xml"/>

  <separator/>

     <group    id="faqs"        label="FAQs">
        &faq-distrib;
        <entry id="faq-build"   source="faq-build.xml"/>
        <entry id="faq-parse"   source="faq-parse.xml"/>
        <entry id="faq-other"   source="faq-other.xml"/>
        &faq-contributing;
     </group>

     <document id="samples"     label="Samples"      source="samples.xml"/>
     <hidden   id="saxcount"    source="saxcount.xml"/>
     <hidden   id="saxprint"    source="saxprint.xml"/>
     <hidden   id="domcount"    source="domcount.xml"/>
     <hidden   id="domprint"    source="domprint.xml"/>
     <hidden   id="memparse"    source="memparse.xml"/>
     <hidden   id="redirect"    source="redirect.xml"/>
     <hidden   id="pparse"      source="pparse.xml"/>
     <hidden   id="stdinparse"  source="stdinparse.xml"/>
     <hidden   id="enumval"     source="enumval.xml"/>
     <hidden   id="createdoc"   source="createdoc.xml"/>
     <hidden   id="sax2count"   source="sax2count.xml"/>
     <hidden   id="sax2print"   source="sax2print.xml"/>
     <hidden   id="senumval"    source="senumval.xml"/>
     <hidden   id="psviwriter"  source="psviwriter.xml"/>
     <hidden   id="scmprint"    source="scmprint.xml"/>

     <document id="api"         label="API Docs"     source="apidocs.xml"/>

  <separator/>

     <external href="ApacheDOMC++Binding.html"     label="DOM C++ Binding"/>

     <document id="program"     label="Programming"  source="program.xml"/>
     <hidden   id="program-sax"           source="program-sax.xml"/>
     <hidden   id="program-sax2"          source="program-sax2.xml"/>
     <hidden   id="program-dom"           source="program-dom.xml"/>
     <hidden   id="dom3"                  source="dom3.xml"/>
     <hidden   id="program-deprecateddom" source="program-deprecateddom.xml"/>
     <hidden   id="schema"                source="schema.xml"/>
     <hidden   id="program-others"        source="program-others.xml"/>

     <document id="migrate"     label="Migration Guide"    source="migration.xml"/>
     <hidden   id="migrate_archive" source="migration_archive.xml"/>
     
  <separator/>

  <document id="feedback"    label="Feedback"     source="feedback.xml"/>
  <document id="bug-report"  label="Bug-Reporting" source="bug-report.xml"/>
  <document id="pdf"         label="PDF Document" source="pdf-c.xml"/>

  <separator/>

   &source_repository;
   &mail_archive_user;
   &mail_archive_devel;

</book>
